name: PlatformIO

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: PlatformIO Run
        uses: karniv00l/platformio-run-action@v1
        with:
          environments: "teensy41"
          targets: "teensy41"
          project-dir: "./"
          project-conf: "./platformio.ini"
          jobs: 6
          silent: false
          verbose: true
          disable-auto-clean: false
      - name: Store Artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: "./.pio/build/teensy41/firmware.hex"
